# pylint: disable=line-too-long,useless-suppression
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from azure.identity import DefaultAzureCredential
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.resource.resources import ResourceManagementClient
from azure.core.exceptions import ResourceNotFoundError
from dotenv import load_dotenv
import os

import sys
import logging

logging.basicConfig(
    level=logging.DEBUG, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", stream=sys.stdout
)


def main():
    load_dotenv()

    # Try to get subscription ID from environment variables
    subscription_id = os.environ.get("AZURE_SUBSCRIPTION_ID")
    if not subscription_id:
        raise ValueError(
            "Subscription ID not found. Please set either SUBSCRIPTION_ID or "
            "AZURE_SUBSCRIPTION_ID environment variable."
        )

    credential = DefaultAzureCredential()

    # Initialize clients
    network_client = NetworkManagementClient(
        credential=credential, subscription_id=subscription_id, logging_enable=True
    )
    resource_client = ResourceManagementClient(
        credential=credential,
        subscription_id=subscription_id,
    )

    resource_group_name = "rg4-yyc"
    location = "eastus2"
    vnet_name = f"bastion-vnet-{resource_group_name}"
    vm_subnet_name = f"vm-subnet-{resource_group_name}"

    # Check if resource group exists, create if not
    try:
        resource_client.resource_groups.get(resource_group_name)
        print(f"Resource group '{resource_group_name}' exists.")
    except ResourceNotFoundError:
        print(f"Resource group '{resource_group_name}' does not exist. Creating...")
        resource_client.resource_groups.create_or_update(resource_group_name, {"location": location})
        print(f"Resource group '{resource_group_name}' created.")

    try:
        # get virtual network
        network_client.virtual_networks.get(resource_group_name, vnet_name)
        print(f"Virtual network '{vnet_name}' already exists.")
    except ResourceNotFoundError:
        print(f"Virtual network '{vnet_name}' does not exist. Creating...")

        # Create virtual network for bastion
        subnet_name = "AzureBastionSubnet"

        # Create VNet with both bastion and VM subnets
        vnet_params = {
            "location": location,
            "address_space": {"address_prefixes": ["10.0.0.0/16"]},
            "subnets": [
                {"name": subnet_name, "address_prefix": "10.0.1.0/27"},
                {"name": vm_subnet_name, "address_prefix": "10.0.2.0/24"},
            ],
        }

        print("Creating virtual network...")
        poller = network_client.virtual_networks.begin_create_or_update(resource_group_name, vnet_name, vnet_params)

        # get continuation token from poller
        continuation_token = poller.continuation_token()

        # reconstruct poller from continuation token
        poller_from_token = network_client.virtual_networks.begin_create_or_update(
            None, None, None, continuation_token=continuation_token
        )

        # poll until done
        vnet_result = poller_from_token.result()
        print(vnet_result)

        print(f"Virtual network '{vnet_name}' created.")


if __name__ == "__main__":
    main()
