# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

"""
FILE: enable_monitoring_metrics.py
DESCRIPTION:
    This sample demonstrate how to monitoring metrics for a managaed cluster,
    producing the same functionality as `az aks update --enable-azure-monitor-metrics -n -g`.
Prerequisites:
    You must have an Azure subscription and an AKS cluster to run this sample.
USAGE:
    python enable_monitoring_metrics.py
    Set the environment variables with your own values before running the sample:
    1) AZURE_SUBSCRIPTION_ID - the subscription id
    2) RESOURCE_GROUP_NAME - the resource group of the resources
    3) AZURE_LOCATION - the location of the resources
    4) AKS_CLUSTER_NAME - the name of the managed cluster you have created
    5) AKS_CLUSTER_ID - the resource id of the managed cluster you have created
    6) MONITOR_WORKSPACE_NAME - the name of the azure monitor workspace
OTHER DEPENDENCE:
    azure-mgmt-monitor==6.0.2
    azure-mgmt-alertsmanagement==2.0.0b2
"""

from azure.identity import DefaultAzureCredential
from azure.core.rest import HttpRequest
from azure.mgmt.containerservice import ContainerServiceClient
from azure.mgmt.monitor import MonitorManagementClient
from azure.mgmt.alertsmanagement import AlertsManagementClient
from dotenv import load_dotenv
import os


def main():
    load_dotenv()
    AZURE_SUBSCRIPTION_ID = os.environ.get("AZURE_SUBSCRIPTION_ID", None)
    RESOURCE_GROUP_NAME = os.environ.get("RESOURCE_GROUP_NAME", None)
    AZURE_LOCATION = os.environ.get("AZURE_LOCATION", None)
    AKS_CLUSTER_NAME = os.environ.get("AKS_CLUSTER_NAME", None)
    AKS_CLUSTER_ID = os.environ.get("AKS_CLUSTER_ID", None)
    MONITOR_WORKSPACE_NAME = os.environ.get("MONITOR_WORKSPACE_NAME", None)

    # Create client
    containerservice_client = ContainerServiceClient(
        subscription_id=AZURE_SUBSCRIPTION_ID,
        credential=DefaultAzureCredential(),
    )
    monitor_client = MonitorManagementClient(
        subscription_id=AZURE_SUBSCRIPTION_ID,
        credential=DefaultAzureCredential(),
    )
    alert_management_client = AlertsManagementClient(
        subscription_id=AZURE_SUBSCRIPTION_ID,
        credential=DefaultAzureCredential(),
    )

    # Create azure monitor workspace
    azure_monitor_workspace_id = monitor_client.azure_monitor_workspaces.create(
        resource_group_name=RESOURCE_GROUP_NAME,
        azure_monitor_workspace_name=MONITOR_WORKSPACE_NAME,
        azure_monitor_workspace_properties={
            "location": AZURE_LOCATION,
        },
    ).id

    # Create data collection endpoint
    data_collection_endpoint_id = monitor_client.data_collection_endpoints.create(
        resource_group_name=RESOURCE_GROUP_NAME,
        data_collection_endpoint_name=f"MSProm-{AZURE_LOCATION}-{AKS_CLUSTER_NAME}",
        body={
            "location": AZURE_LOCATION,
            "kind": "Linux",
            "properties": {"description": "Data Collection Endpoint for AKS"},
        },
    ).id

    # Create data collection rule
    data_collection_rule_id = monitor_client.data_collection_rules.create(
        resource_group_name=RESOURCE_GROUP_NAME,
        data_collection_rule_name=f"MSProm-{AZURE_LOCATION}-{AKS_CLUSTER_NAME}",
        body={
            "location": AZURE_LOCATION,
            "kind": "Linux",
            "properties": {
                "dataCollectionEndpointId": data_collection_endpoint_id,
                "dataSources": {
                    "prometheusForwarder": [
                        {
                            "name": "PrometheusDataSource",
                            "streams": ["Microsoft-PrometheusMetrics"],
                            "labelIncludeFilter": {},
                        }
                    ]
                },
                "dataFlows": [{"destinations": ["MonitoringAccount1"], "streams": ["Microsoft-PrometheusMetrics"]}],
                "description": "DCR description",
                "destinations": {
                    "monitoringAccounts": [
                        {"accountResourceId": azure_monitor_workspace_id, "name": "MonitoringAccount1"}
                    ]
                },
            },
        },
    ).id

    # Create data collection rule association
    monitor_client.data_collection_rule_associations.create(
        resource_uri=AKS_CLUSTER_ID,
        association_name="ContainerInsightsMetricsExtension",
        body={
            "location": AZURE_LOCATION,
            "properties": {
                "dataCollectionRuleId": data_collection_rule_id,
                "description": "Promtheus data collection association between DCR, DCE and target AKS resource",
            },
        },
    )

    # Get rule templates, logic referred from CLI: 
    # https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/recordingrules/create.py
    response = alert_management_client._send_request(
        HttpRequest(
            "GET",
            f"{azure_monitor_workspace_id}/providers/microsoft.alertsmanagement/alertRuleRecommendations?api-version=2023-01-01-preview",
        )
    )
    data = response.json()
    filtered_templates = [
        template
        for template in data.get("value", [])
        if template.get("properties", {}).get("alertRuleType", "").lower()
        == "microsoft.alertsmanagement/prometheusrulegroups"
        and isinstance(template.get("properties", {}).get("rulesArmTemplate", {}).get("resources"), list)
        and all(
            isinstance(rule, dict) and "record" in rule and "expression" in rule
            for resource in template["properties"]["rulesArmTemplate"]["resources"]
            if resource.get("type", "").lower() == "microsoft.alertsmanagement/prometheusrulegroups"
            for rule in resource.get("properties", {}).get("rules", [])
        )
    ]

    # Create prometheus rule groups
    alert_management_client.prometheus_rule_groups.create_or_update(
        resource_group_name=RESOURCE_GROUP_NAME,
        rule_group_name=f"NodeRecordingRulesRuleGroup-{AKS_CLUSTER_NAME}",
        parameters={
            "location": AZURE_LOCATION,
            "type": "Microsoft.AlertsManagement/prometheusRuleGroups",
            "properties": {
                "scopes": [azure_monitor_workspace_id, AKS_CLUSTER_ID],
                "enabled": True,
                "clusterName": AKS_CLUSTER_NAME,
                "interval": "PT1M",
                "rules": filtered_templates[0]["properties"]["rulesArmTemplate"]["resources"][0]["properties"]["rules"],
            },
        },
    )

    alert_management_client.prometheus_rule_groups.create_or_update(
        resource_group_name=RESOURCE_GROUP_NAME,
        rule_group_name=f"KubernetesRecordingRulesRuleGroup-{AKS_CLUSTER_NAME}",
        parameters={
            "location": AZURE_LOCATION,
            "type": "Microsoft.AlertsManagement/prometheusRuleGroups",
            "properties": {
                "scopes": [azure_monitor_workspace_id, AKS_CLUSTER_ID],
                "enabled": True,
                "clusterName": AKS_CLUSTER_NAME,
                "interval": "PT1M",
                "rules": filtered_templates[1]["properties"]["rulesArmTemplate"]["resources"][0]["properties"]["rules"],
            },
        },
    )

    # Update Managed Cluster
    managed_cluster = containerservice_client.managed_clusters.begin_create_or_update(
        resource_group_name=RESOURCE_GROUP_NAME,
        resource_name=AKS_CLUSTER_NAME,
        parameters={"location": AZURE_LOCATION, "azureMonitorProfile": {"metrics": {"enabled": True}}},
    ).result()


if __name__ == "__main__":
    main()
